export const GET_PIRCINGS_SUCCESS = "GET_PIRCINGS_SUCCESS";
export const GET_PIRCINGS_FAIL = "GET_PIRCINGS_FAIL";
export const GET_PIRCING_SUCCESS = "GET_PIRCING_SUCCESS";
export const GET_PIRCING_FAIL = "GET_PIRCING_FAIL";
