export const GET_BRAZALETES_SUCCESS = "GET_BRAZALETES_SUCCESS";
export const GET_BRAZALETES_FAIL = "GET_BRAZALETES_FAIL";
export const GET_BRAZALETE_SUCCESS = "GET_BRAZALETE_SUCCESS";
export const GET_BRAZALETE_FAIL = "GET_BRAZALETE_FAIL";
