export const GET_TOBILLERAS_FAIL = "GET_TOBILLERAS_FAIL";
export const GET_TOBILLERAS_SUCCESS = "GET_TOBILLERAS_SUCCESS";
export const GET_TOBILLERASADMIN_FAIL = "GET_TOBILLERASADMIN_FAIL";
export const GET_TOBILLERASADMIN_SUCCESS = "GET_TOBILLERASADMIN_SUCCESS";
export const GET_TOBILLERA_FAIL = "GET_TOBILLERA_FAIL";
export const GET_TOBILLERA_SUCCESS = "GET_TOBILLERA_SUCCESS";
export const GET_TOBILLERAS_NAME_SUCCESS = "GET_TOBILLERAS_NAME_SUCCESS";
export const GET_TOBILLERAS_NAME_FAIL = "GET_TOBILLERAS_NAME_FAIL";
export const GET_TOBILLERAS_SIZE_SUCCESS = "GET_TOBILLERAS_SIZE_SUCCESS";
export const GET_TOBILLERAS_SIZE_FAIL = "GET_TOBILLERAS_SIZE_FAIL";
export const GET_TOBILLERAS_PUREZA_SUCCESS = "GET_TOBILLERAS_PUREZA_SUCCESS";
export const GET_TOBILLERAS_PUREZA_FAIL = "GET_TOBILLERAS_PUREZA_FAIL";
export const GET_TOBILLERAS_PESONETO_SUCCESS =
  "GET_TOBILLERAS_PESONETO_SUCCESS";
export const GET_TOBILLERAS_PESONETO_FAIL = "GET_TOBILLERAS_PESONETO_FAIL";
export const GET_TOBILLERAS_PRECIOUNIDAD_SUCCESS =
  "GET_TOBILLERAS_PRECIOUNIDAD_SUCCESS";
export const GET_TOBILLERAS_PRECIOUNIDAD_FAIL =
  "GET_TOBILLERAS_PRECIOUNIDAD_FAIL";
export const GET_SEARCH_TOBILLERA_SUCCESS = "GET_SEARCH_TOBILLERAS_SUCCESS";
export const GET_SEARCH_TOBILLERA_FAIL = "GET_SEARCH_TOBILLERAS_FAIL";
