export const GET_TOBILLERAS_SUCCESS = "GET_TOBILLERAS_SUCCESS";
export const GET_TOBILLERAS_FAIL = "GET_TOBILLERAS_FAIL";
export const GET_TOBILLERA_SUCCESS = "GET_TOBILLERA_SUCCESS";
export const GET_TOBILLERA_FAIL = "GET_TOBILLERA_FAIL";
